name: Deploy to Streamlit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit

    - name: Deploy to Streamlit
      env:
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
      run: streamlit run excel_sample.py
